#!/bin/bash

export GOPATH=`pwd`
export PATH="$PATH:$GOPATH/bin"

(
cd github.com/zgagnon/authrouteservice
echo `pwd`
go get github.com/onsi/ginkgo
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
go get github.com/tools/godep

godep restore
ginkgo main proxy
)
