resources:
  - name: auth-route-service
    type: git
    source:
        uri: git@github.com:zgagnon/authrouteservice.git
        branch: master
        private_key: {{ssh-key}}

jobs:
  - name: test
    plan:
      - get: auth-route-service
        trigger: true
      - task: unit
        file: auth-route-service/ci/test.yml

  - name: push
    plan:
      - get: auth-route-service
        passed: [test]
        trigger: true
      - task: push
        file: ci/push.yml
